"""Regenerar migraciones

Revision ID: 53305d5a1dd6
Revises: 
Create Date: 2024-08-10 19:05:52.799615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53305d5a1dd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.drop_column('equipo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
